# Generated by Django 3.2.9 on 2021-12-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_outpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='postiion',
            new_name='position',
        ),
    ]
