# Generated by Django 3.2.9 on 2021-12-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_outpost', '0003_offer_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
